### ISSUE TITLE
Could you notice when you can share pretrained model?

### ISSUE THREAD

**Issue by yerang823** [felixrosberg/FaceDancer#1]
Could you notice when you can share pretrained model(FaceDancer-C.h5) ?
I'd really appreciate it :)

**Comment by zhouzikang** [comment]
Me too.

**Comment by MallaRupesh** [comment]
#end of the month

Waiting for it.

**Comment by felixrosberg** [comment]
Hello all!

You can now find the models over at [Hugging Face](https://huggingface.co/felixrosberg/FaceDancer).

Including the one trained on high resolution images.
