### ISSUE TITLE
enviroment.yml

### ISSUE THREAD

**Issue by hichemfelouat** [felixrosberg/FaceDancer#10]
I tried to use the FaceDancer project. However, I faced many issues. There is a problem with creating a new environment from the provided environment!

**Comment by hichemfelouat** [comment]
Lunux

> > I tried to use the FaceDancer project. However, I faced many issues. There is a problem with creating a new environment from the provided environment!
> 
> What is your OS - Windows or Linux?

Linux

**Comment by hichemfelouat** [comment]
> ```python
> gpus 
> ```

Thank you so much for your efforts; our server works on ubuntu 18.04 with many GPUs. I tried to follow your instruction, and the environment is created correctly but still not working. I think if you create a Google colab notebook, it will be helpful for us and others who want to use this project.

**Comment by felixrosberg** [comment]
Hello @hichemfelouat,

I see @netrunner-exe have made a great effort. The only thing I can think of is trying to install all the libraries separately as I suspect that latest version for each should work just fine assuming you us python 3.8. Also what exactly is not working? You said environment is created correctly but it is still not working? Are you trying to run any specific scripts? Also what error does this yield?

Regards Collab demo: I would like to provide one but is currently swamped until next year. For using  the pretrained models in a custom Collab notebook, uploading the models to your drive and mounting the drive + following the custom script instruction should work for running the models using Collab.

**Comment by felixrosberg** [comment]
I can add that there is a Colab demo available now if you missed it. Will close this issue for now.
