### ISSUE TITLE
No module named 'retinaface.models'

### ISSUE THREAD

**Issue by kambiannan** [felixrosberg/FaceDancer#13]
Getting this error
`(facedancer) D:\FaceDancer>python test_video_swap_multi.py --facedancer_path "./model_zoo/FaceDancer_config_c_HQ.h5" --vid_path "input/vid.mp4" --swap_source "input/vid.jpg" --vid_output "results/swapped_video.mp4"`

 ` File "D:\FaceDancer\test_video_swap_multi.py", line 13, in <module>
    from retinaface.models import *
ModuleNotFoundError: No module named 'retinaface.models'`

Although I have copied RetinaFace-Res50.h5 inside the ./retinaface dir.

**Comment by felixrosberg** [comment]
This error is not related to you having RetinFace-50.h5 or not. The error is due to failure of importing the models.py file inside the retinaface directory (retinaface/models.py). I just ran the video swap script quickly to make sure it is correct and it works on my side. Have you changed or moved the files in anyway?

**Comment by kambiannan** [comment]
File are all present.  Let me see what else I can find. Thanks

(FaceDancer) D:\FaceDancer\retinaface>dir
12/26/2022  12:00 AM    <DIR>          .
12/26/2022  12:00 AM    <DIR>          ..
12/25/2022  11:41 PM            12,276 anchor.py
12/25/2022  11:41 PM            10,940 models.py
12/25/2022  11:41 PM               989 ops.py
10/20/2022  07:29 AM       110,218,760 RetinaFace-Res50.h5
               4 File(s)    110,242,965 bytes
               2 Dir(s)  710,748,274,688 bytes free
(FaceDancer) D:\FaceDancer\retinaface>`

**Comment by kambiannan** [comment]
So I solved the issue with adding an empty **__init__.py** file inside the retinaface folder. Not a python dev. Just learning. Thank you for this

**Comment by felixrosberg** [comment]
Closing as this should be fixed in the code base aswell.
