### ISSUE TITLE
IFSR for PyTorch implementation

### ISSUE THREAD

**Issue by max-vasyuk** [felixrosberg/FaceDancer#20]
Hello, could you please tell me which Arcface layers to use for the IFSR implementation, if we are talking about PyTorch implementation. I don't quite understand how to find the correspondence between the models in Keras and in Pytorch. Thanks in advance!

**Comment by felixrosberg** [comment]
Hi,

I used outputs from each ResNet-block in a ResNet50 during the initial analysis. We ended up choosing the output from the 3rd block up to the 14th block (Or block 2 to 13 if you go with index start 0, as described in the paper).

Now what I noticed is if you use ArcFace from InsightFace, then ResNet34 seem to match the architecture of Keras/TensorFlows ResNet50. Why that is, I do not know. But from what I gather, ResNet34 in PyTorch using 3rd to 14th block output for IFSR should match the TensorFlow implementation.

Hope this helps.

**Comment by max-vasyuk** [comment]
@felixrosberg Thank you so much!

**Comment by felixrosberg** [comment]
Hello, small update regarding the PyTorch version: Fixed identity convergence and got it working. I will in the coming weeks clean the code and train a few models (Including a 3D aware version) and then hopefully provide that on github asap. A note on IFSR, I found that it seem to work without margins, meaning no need to worry that much what the margins should be and where. I suspect however that you should not use the deepest layers where the similarity is closer to source (See Figure. 6 in the paper).
