### ISSUE TITLE
Face occlusion detection?

### ISSUE THREAD

**Issue by antonsanchez** [felixrosberg/FaceDancer#27]
If I just want to detect if a face is occluded or not, how can I do that?

Thanks!

**Comment by felixrosberg** [comment]
Hello @antonsanchez !

FaceDancer learns automatically to take occlusion into account when manipulating the face (This is limited to really large occlusions, where to may notice a face on top of the occlusion).

There is no direct use of occlusion detection. Considering the above behavior, it is theoretically possible to use some features/information inside a pretrained FaceDancer for zero-shot occlusion detection. How I can sadly not answer.
