### ISSUE TITLE
Ideal resolution and tips to get best results

### ISSUE THREAD

**Issue by terencetay** [felixrosberg/FaceDancer#28]
Hi, I've seen this warning in the readme and on the demo webpage: "Source image with too high resolution may not work properly!" Could you clarify what resolution is "too high"?

Or more importantly, what is the ideal resolution for FaceDancer to produce the best results?

So far, I've been using FaceDancer on images with resolution 1000 pixels on the long side. The results have been mostly good. But with videos, I've been getting poor results. The face in the output video often glitch from frame to frame. I've tested with videos that are 1280x720 (720p) and 640x480 (480p) and got poor results at both resolutions. Do you have any tips on how to get the best possible output from FaceDancer, similar to the ones you showed in your published examples?

Thank you.

**Comment by felixrosberg** [comment]
The ideal resolution for FaceDancer is 256x256, but the above comment is about extracting the source face from an image with RetinaFace. Now I am not sure what the ideal resolution is, but the source will be aligned and cropped to 112x112, meaning you do not need high resolution images.

For stability and detecting target faces however you have to play around with the detection_scale variable in the code, which rescales large images. You can however adjust this to allow larger images or smaller as input to RetinaFace. The predicted landmarks will be rescaled according to the original resolution. What the best is I am not sure. I just assume that too high resolution may cause RetinaFace to struggle. Images I show is either aligned with the detection_scale or not, I actually can not remember. For videos (if that is what you mean) I just used the standard script presented in this repo.

**Comment by terencetay** [comment]
Thank you for the tips. That's helpful.
