### ISSUE TITLE
Test swaps work, but can't get crop_align to work.

### ISSUE THREAD

**Issue by hdlcbend** [felixrosberg/FaceDancer#32]
Forgive me if the fix is simple, but I haven't coded in 20 years since i did a little HTML and javascript. I have no experience with python until the last couple months.

so,if i run it as 

python dataset/crop_align.py --data_dir /dataset --target_dir train_data_sets/DATASET --device_id 0 --im_size 256 --min_size 128 --shrink_factor 1.0

which as far as i can tell is correct.
I get this error 

Traceback (most recent call last):
  File "dataset/crop_align.py", line 6, in <module>
    from utils.utils import norm_crop
ModuleNotFoundError: No module named 'utils'

I use chatgpt to solve most of my issues, but this one hasn't worked out. It told me to add sys path in the crop_align.py file, for utils, so i did that. and when i did, i got the same error, except for "networks". GPT tells me to add a sys path for that as well, but it doesn't fix it. 

I made a copy of crop_align.py in the root facedancer dir, and I get this error instead:

Traceback (most recent call last):
  File "crop_align.py", line 40, in <module>
    face_detector = load_model("retinaface/RetinaFace_Res50.h5", custom_objects={"FPN": FPN,
  File "C:\Users\kella\anaconda3\envs\facedancer\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\kella\anaconda3\envs\facedancer\lib\site-packages\keras\saving\save.py", line 226, in load_model
    raise IOError(
OSError: No file or directory found at retinaface/RetinaFace_Res50.h5

extra info: im running the code from anaconda powershell, on windows 11, 16gb ram, geforce 3060 laptop GPU @ 6gbVRAM
I'm really kinda stuck here. The test swaps are cool, but far from perfect. Really hoping the training will improve it. 
Thanks in advance for any help you can provide, and I apologize for any ignorance on my part! :)

**Comment by zengjingming** [comment]
I put this at the front:

`import os
dir_path = os.path.dirname(os.path.realpath(__file__)) # 获取当前目录
parent_dir_path = os.path.abspath(os.path.join(dir_path, os.pardir)) # 获取上级目录

import sys
sys.path.append(parent_dir_path) # 添加上级目录`

**Comment by hdlcbend** [comment]
I'll give this a try and report the results. thanks!

**Comment by hdlcbend** [comment]
After a little messing around, I got it to work, thanks for the help.
