### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by liushifu12138** [felixrosberg/FaceDancer#35]
thanks your job? Why not just write in pytorch? tf made a lot of mistakes. Does tf have to be the highest version of CUDA?

**Comment by felixrosberg** [comment]
Well I started of with knowledge in TF. Started my work their. I have since switched to PyTorch. I tried reimplement FaceDancer in PyTorch. But ran into a few issues. However I am working on some other stuff which may outperform FaceDancer.

**Comment by 5RJ** [comment]
Hi, thanks for your work! Is there new work outperform FanceDancer now?  and in pytorch ?
