### ISSUE TITLE
Mutl threads running

### ISSUE THREAD

**Issue by Liam6666** [felixrosberg/FaceDancer#38]
When I created mutl threads runing, It cannot improve efficiency.
It's really sad

**Comment by Liam6666** [comment]
![image](https://github.com/felixrosberg/FaceDancer/assets/32121394/17a9509a-75f5-4d2e-a3ee-c19fe9b7084b)

**Comment by Liam6666** [comment]
How can we improve efficiency and make machines emit loud noise

**Comment by Liam6666** [comment]
I had a new idea while dreaming.

![image](https://github.com/felixrosberg/FaceDancer/assets/32121394/bf689f76-7f87-491c-b1d6-cc3ec059872b)

We can load multiple process, to prepare 'face swap' the frame image.
‘Space for time’

**Comment by Liam6666** [comment]
![image](https://github.com/felixrosberg/FaceDancer/assets/32121394/00f1ab0a-f6a0-476d-a453-b7d154c74112)
(This is just pseudocode)

**Comment by felixrosberg** [comment]
If you are after improved efficiency. Doing batch detection and batch alignment on the GPU is probably the way. I have started to address these issues for a PyTorch based framework. Meaning I will probably not implement it for TensorFlow/this repo.

**Comment by Liam6666** [comment]
> If you are after improved efficiency. Doing batch detection and batch alignment on the GPU is probably the way. I have started to address these issues for a PyTorch based framework. Meaning I will probably not implement it for TensorFlow/this repo.


Thanks for your reply, good job man!
