### ISSUE TITLE
Any news about the PyTorch version ? 

### ISSUE THREAD

**Issue by makinyilmaz** [felixrosberg/FaceDancer#4]
Thanks for this amazing work! I wonder if you are close to solve the issues you mentioned.

Best

Akın

**Comment by felixrosberg** [comment]
Hi @makinyilmaz 

As of now, some recent testing is still showing problems. For now I will have to set the PyTorch version aside due to other projects.
I will get back to it, just not sure when.

**Comment by felixrosberg** [comment]
Hello, small update regarding the PyTorch version: Fixed identity convergence and got it working. I will in the coming weeks clean the code and train a few models (Including a 3D aware version) and then hopefully provide that on github asap.
