### ISSUE TITLE
Is it possible to finetune pretrained model?

### ISSUE THREAD

**Issue by baejun10** [felixrosberg/FaceDancer#43]
I can't find load pretrained model option at train.py
Have you ever tried to finetune model?

**Comment by felixrosberg** [comment]
Hi, I need more information to help out with troubles loading the model.

Kinda, I have made finetunings for a DeepFake competition. Tried to make some refinements. Other than that, nope. :)

**Comment by baejun10** [comment]
I want to finetune your pretrained model(FaceDancer_config_c_HQ.h5).
So, I need to load h5 model. but, there is no function to load h5 model  in train.py.
Also, I assume that FaceDancer_config_c_HQ.h5 may not have discriminator but only generator parts. Can you share your whole files?

**Comment by baejun10** [comment]
p.s.  I wrote codes that load pretrained model to G(Generator variable). And I tried to finetune model with asian faces. 
It worked well without pretrained Discriminator!

**Comment by huysieunhan2910** [comment]
> p.s. I wrote codes that load pretrained model to G(Generator variable). And I tried to finetune model with asian faces. It worked well without pretrained Discriminator!

can you share file ? thannks
