### ISSUE TITLE
Low GPU utilization

### ISSUE THREAD

**Issue by johnrom1243** [felixrosberg/FaceDancer#8]
I managed to make it work, however it's really slow at around 2.40 s/it and my GPU is hovering around 20 percent utilization, Im running a 3080 12gb

**Comment by felixrosberg** [comment]
Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.

**Comment by felixrosberg** [comment]
> Perhaps question was about video inference?

Ah yes that explains it. Currently the face detector can only handle batch size 1. Which sucks I know. I have plans to adopt this to handle an arbitrary batch size and try to make a buffer of frames that the FaceDancer can draw from. Which I can see being problematic solve when dealing with several faces that needs to be blended into the frame.

**Comment by vespersland** [comment]
> > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> 
> Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.

Hi netrunner, how can I contact you privately for info? thanks in advance

**Comment by netrunner-exe** [comment]
> > > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> > 
> > 
> > Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.
> 
> Hi netrunner, how can I contact you privately for info? thanks in advance

Hi, you can contact in my profile

**Comment by vespersland** [comment]
> > > > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> > > 
> > > 
> > > Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.
> > 
> > 
> > Hi netrunner, how can I contact you privately for info? thanks in advance
> 
> Hi, you can contact in my profile

On git there is no chance to contact you with a private message

**Comment by netrunner-exe** [comment]
> > > > > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> > > > 
> > > > 
> > > > Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.
> > > 
> > > 
> > > Hi netrunner, how can I contact you privately for info? thanks in advance
> > 
> > 
> > Hi, you can contact in my profile
> 
> On git there is no chance to contact you with a private message

There is an email address on my page. In general, it is better to ask questions related to FaceDancer directly to the author of the code, since I am not developer of this project.

**Comment by vespersland** [comment]
> > > > > > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> > > > > 
> > > > > 
> > > > > Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.
> > > > 
> > > > 
> > > > Hi netrunner, how can I contact you privately for info? thanks in advance
> > > 
> > > 
> > > Hi, you can contact in my profile
> > 
> > 
> > On git there is no chance to contact you with a private message
> 
> There is an email address on my page. In general, it is better to ask questions related to FaceDancer directly to the author of the code, since I am not developer of this project.

Thanks but the topic is not about this project,anyway I don't see any email address maybe your profile is private

**Comment by vespersland** [comment]
> > > > > > Hm, what batch size do you use? Could be some improvements that needs to be done. But when I trained my models it utilized the whole GPU with 1.1 it/s on batch size 10. That is a single 3090.
> > > > > 
> > > > > 
> > > > > Perhaps question was about video inference? If yes, then it will not actually work much to use the GPU - perhaps the same problem that was in SimSwap - one frame, processing, the next frame - processing. A possible solution is to implement batch processing of frames, operating on a batch size to avoid OOM. This would greatly reduce video processing time and increase GPU utilization accordingly.
> > > > 
> > > > 
> > > > Hi netrunner, how can I contact you privately for info? thanks in advance
> > > 
> > > 
> > > Hi, you can contact in my profile
> > 
> > 
> > On git there is no chance to contact you with a private message
> 
> There is an email address on my page. In general, it is better to ask questions related to FaceDancer directly to the author of the code, since I am not developer of this project.

Nothing to do I couldn't find your email anywhere.please send me your email address (vespersland@gmail.com)
